# train and val datasets
GPUS: 0, 1
WORKERS: 16
LOG_DIR: ./log
TENSORBOARD_DIR: ./tensorboard
MODEL_DIR: ./checkpoints
RESULT_DIR: ./results
VERBOSE: True
TAG: ""

DATASET:
  NAME: Charades
  TRAIN: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/text_data/Charades-STA/charades_sta_train.txt
  VAL: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/text_data/Charades-STA/charades_sta_test.txt
  TEST: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/text_data/Charades-STA/charades_sta_test.txt

  ANNOTATION_PATH: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/Charades_v1_cache/Annotation

  ANCHOR_PATH: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/Anchor/charades.txt

  VIDEO_CACHE: /nfsc/aies_core_id10061778_vol1001_dev/backup/xionghaoliang660/datasets/Moment_Retrieval/Charades_v1_cache/

  BLOCK_SIZE: 30

  NO_VAL: True

LOSS:
  NA: 5
  ANCHOR_T: 4.0
  ALPHA: 1
  BETA: 5
  GAMMA: 0.3
  SCALE: 0.1

TRAIN:
  LR: 0.00001
  WEIGHT_DECAY: 0
  FACTOR: 0.8
  PATIENCE: 20
  MAX_EPOCH: 20
  BATCH_SIZE: 4
  STEP_ACCUMULATE: 1
  SHUFFLE: True
  CONTINUE: False
  FP16: False
  FINE_TUNE: False

TEST:
  BATCH_SIZE: 16
  RECALL: 1,5
  TIOU: 0.5,0.7
  NMS_THRESH: 0.5

MODEL:
  NAME: M-YOLO
  TEXT_ATTN_LAYER: 3
  CRO_ATTN_LAYER: 2
  CON_ALPHA: 0.2
  CON_BETA: 0.3
  MARGIN: 0.5

CUDNN:
  DETERMINISTIC: False
  BENCHMARK: True